### ISSUE TITLE
flutter config --enable-linux-desktop doesn't apply before building

### ISSUE THREAD

**Issue by mpconte** [britannio/action-install-flutter#1]
With the sample workflow:

```
name: Build Flutter Demo for Linux

on:
  workflow_dispatch:  
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2      
     
      - uses: britannio/action-install-flutter@v1.1
      
      - run: |
          sudo apt-get update -y
          sudo sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev 
      
      - name: Enable Linux desktop development and build
        run: |          
          flutter config --enable-linux-desktop                
          flutter packages get
          flutter build linux
```

Returns the following error on **flutter build linux**:

![image](https://user-images.githubusercontent.com/7958011/154341503-1c22a04b-06d9-483f-8f82-34651583f767.png)
